Revert "fix: Set NVreg_PreserveVideoMemoryAllocations=1 on Nvidia and Hybrid"
pop-os/nvidia-graphics-drivers pull request #128
Opened 2021-11-18 19:18 UTC by crawfxrd

This reverts commit de515f69a4816b6e11633faba2d11b1f2a738c55.

`NVreg_PreserveVideoMemoryAllocations` should not be used with S0ix.
Instead, these systems must enable S0ix-based power management with
`NVreg_EnableS0ixPowerManagement=1` [\[1\]].

Configuring these settings must be moved to system76-power or
system76-driver to handle this difference between sleep modes.

[\[1\]]: https://download.nvidia.com/XFree86/Linux-x86_64/470.86/README/powermanagement.html#PreserveAllVide719f0

2021-11-18 20:28 UTC, jackpot51 approved these changes

2021-11-19 16:17 UTC, jacobgkau commented
This isn't currently in a staging repo even though it shows as built, may need to test locally.

2021-11-19 19:25 UTC, 13r0ck commented
This can't be approved until it can be pulled from a staging repo, but after some preliminary testing by building locally with pop-os/system76-power#293 this works correctly.

2021-11-22 21:10 UTC, 13r0ck approved these changes
Tested on Gaze16 and Addw2 on all 3 graphics profiles w/ pop-os/system76-power#293 . Sleep still works correctly.

2021-11-22 22:38 UTC, 13r0ck requested changes
Suspend doesn't work correctly [on kudu6](https://github.com/pop-os/system76-power/pull/293#pullrequestreview-813082752). This will have to wait until that is fixed.

2021-11-23 00:28 UTC, 13r0ck approved these changes
Changes requested in error. There are no regressions here.

2021-11-23 02:44 UTC, merged