495.46
pop-os/nvidia-graphics-drivers pull request #132
Opened 2021-12-15 20:21 UTC by jackpot51

- Sync packaging with Ubuntu
- Update to 495.46 from https://www.nvidia.com/Download/driverResults.aspx/184248/en-us

2021-12-16 01:33 UTC, Slackadays commented
Does this mark a lasting change from the Nvidia "production" branch to the "feature" branch?

2021-12-16 15:53 UTC, jackpot51 commented
@Slackadays our intention is to always provide the newest NVIDIA driver that passes our tests.

2021-12-16 18:41 UTC, leviport commented
I think something didn't get updated right. After adding the `495.46` branch, apt seems to think the update is for `nvidia-driver-460`:
```
$ sudo apt update && sudo apt upgrade
Hit:1 http://apt.pop-os.org/proprietary impish InRelease
Hit:2 http://apt.pop-os.org/release impish InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu impish InRelease
Hit:4 http://apt.pop-os.org/staging/495.46 impish InRelease
Hit:5 http://apt.pop-os.org/staging/5.15.8 impish InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu impish-security InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu impish-updates InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu impish-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  nvidia-driver-460
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

2021-12-16 19:25 UTC, jackpot51 commented
@leviport it provides transitional packages for older versions. system76-driver still depends on nvidia-driver-460.

2021-12-16 19:31 UTC, leviport commented
Do we want it to require a `full-upgrade` then? I thought that was usually undesirable on Pop.

2021-12-16 19:52 UTC, jackpot51 commented
> Do we want it to require a `full-upgrade` then? I thought that was usually undesirable on Pop.

I think it usually has required that. Can you try running `sudo apt upgrade nvidia-driver-460` to see why it is held back?

2021-12-16 19:57 UTC, leviport commented
I'm usually able to install them on Pop with just a `sudo apt upgrade`

```
$ sudo apt upgrade nvidia-driver-460
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-driver-495 : Depends: libnvidia-gl-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: nvidia-dkms-495 (<= 495.46-1)
                     Depends: nvidia-dkms-495 (>= 495.46)
                     Depends: nvidia-kernel-common-495 (<= 495.46-1) but it is not going to be installed
                     Depends: nvidia-kernel-common-495 (>= 495.46) but it is not going to be installed
                     Depends: nvidia-kernel-source-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: libnvidia-compute-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: libnvidia-extra-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: nvidia-compute-utils-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: libnvidia-decode-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: libnvidia-encode-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: nvidia-utils-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: xserver-xorg-video-nvidia-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: libnvidia-cfg1-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Depends: libnvidia-fbc1-495 (= 495.46-1pop0~1639598889~21.10~03e1b76) but it is not going to be installed
                     Recommends: libnvidia-compute-495:i386 (= 495.46-1pop0~1639598889~21.10~03e1b76)
                     Recommends: libnvidia-decode-495:i386 (= 495.46-1pop0~1639598889~21.10~03e1b76)
                     Recommends: libnvidia-encode-495:i386 (= 495.46-1pop0~1639598889~21.10~03e1b76)
                     Recommends: libnvidia-fbc1-495:i386 (= 495.46-1pop0~1639598889~21.10~03e1b76)
                     Recommends: libnvidia-gl-495:i386 (= 495.46-1pop0~1639598889~21.10~03e1b76)
E: Broken packages
```

2021-12-16 21:46 UTC, jackpot51 commented
Oh I think I might be missing the 470 transition packages, I will add them!

2021-12-16 21:48 UTC, jackpot51 commented
Latest commit does just that @leviport

2021-12-17 16:39 UTC, leviport requested changes
I'm still seeing dependency issues after https://github.com/pop-os/nvidia-graphics-drivers/pull/132/commits/b0fc88d4f20482fd542c6b163c16337bcb79d95f. 

```
[levi@levioryx:~]$ sudo apt update && sudo apt upgrade
Hit:1 http://apt.pop-os.org/proprietary impish InRelease
Hit:2 http://apt.pop-os.org/release impish InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu impish InRelease
Hit:4 http://apt.pop-os.org/staging/495.46 impish InRelease
Hit:5 http://apt.pop-os.org/staging/5.15.8 impish InRelease
Get:6 http://us.archive.ubuntu.com/ubuntu impish-security InRelease [110 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu impish-updates InRelease [110 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu impish-backports InRelease [101 kB]
Fetched 321 kB in 1s (518 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
30 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  libnvidia-common-495 nvidia-kernel-common-495
The following packages have been kept back:
  libnvidia-cfg1-470 libnvidia-compute-470 libnvidia-compute-470:i386 libnvidia-decode-470 libnvidia-decode-470:i386 libnvidia-encode-470 libnvidia-encode-470:i386 libnvidia-extra-470 libnvidia-fbc1-470
  libnvidia-fbc1-470:i386 libnvidia-gl-470 libnvidia-gl-470:i386 nvidia-compute-utils-470 nvidia-dkms-470 nvidia-driver-460 nvidia-driver-470 nvidia-kernel-source-470 nvidia-utils-470
  xserver-xorg-video-nvidia-470
The following packages will be upgraded:
  gnome-settings-daemon gnome-settings-daemon-common gnome-settings-daemon-dev libnvidia-common-470 libpop-upgrade-gtk nvidia-kernel-common-470 openjdk-11-jre openjdk-11-jre-headless pop-upgrade
  ubuntu-release-upgrader-core update-manager-core
11 upgraded, 2 newly installed, 0 to remove and 19 not upgraded.
2 standard security updates
Need to get 65.0 MB of archives.
After this operation, 2,225 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
[levi@levioryx:~]$ sudo apt upgrade nvidia-driver-460
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-driver-495 : Depends: nvidia-dkms-495 (<= 495.46-1)
                     Depends: nvidia-dkms-495 (>= 495.46)
                     Depends: nvidia-kernel-common-495 (<= 495.46-1) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
E: Broken packages
```

When trying to update in pop-shop, I get an error dialog with the following text:
```
The following packages have unmet dependencies:
  nvidia-driver-470: Depends: libnvidia-gl-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: nvidia-kernel-source-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: libnvidia-compute-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: libnvidia-extra-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: nvidia-compute-utils-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: libnvidia-decode-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: libnvidia-encode-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: nvidia-utils-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: xserver-xorg-video-nvidia-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: libnvidia-cfg1-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Depends: libnvidia-fbc1-470 (= 470.86-1pop0~1637635465~21.10~47710c4) but 495.46-1pop0~1639691264~21.10~b0fc88d is to be installed
                     Recommends: libnvidia-compute-470:i386 (= 470.86-1pop0~1637635465~21.10~47710c4)
                     Recommends: libnvidia-decode-470:i386 (= 470.86-1pop0~1637635465~21.10~47710c4)
                     Recommends: libnvidia-encode-470:i386 (= 470.86-1pop0~1637635465~21.10~47710c4)
                     Recommends: libnvidia-fbc1-470:i386 (= 470.86-1pop0~1637635465~21.10~47710c4)
                     Recommends: libnvidia-gl-470:i386 (= 470.86-1pop0~1637635465~21.10~47710c4)
```

We'll definitely need to make sure the update is installable via pop-shop.

2021-12-17 17:14 UTC, jackpot51 commented
Should be fixed with the latest commit 0dd1e4c

2021-12-17 19:46 UTC, 13r0ck requested changes
Steam fails to launch on Galp5 21.10

1. Fresh install of 21.10
2. Install all updates
3. Install steam
4. Steam launches

</br>

1. Fresh install 21.10
2. Install all updates
3. Install this PR
4. Install Steam
4. Steam __Does Not__ work

2021-12-17 20:04 UTC, jackpot51 commented
Thanks @13r0ck, I will check it out on a galp5.

2021-12-17 20:24 UTC, 13r0ck commented
I cannot get any terminal output, because steam launches correctly via the terminal. Once launched via terminal it fixes the issue and works via the launcher

2021-12-17 20:25 UTC, jackpot51 commented
`journalctl -b 0 -t steam.desktop` might work

2021-12-17 20:44 UTC, jackpot51 commented
I am getting this output from that command:

```
Dec 17 13:43:35 jeremy-galp5 steam.desktop[3072]: /usr/share/themes/Pop/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'
Dec 17 13:43:35 jeremy-galp5 steam.desktop[3072]: /usr/share/themes/Pop/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
```

2021-12-17 20:47 UTC, jackpot51 commented
This might be related to the ifr1 library going away.

2021-12-17 21:10 UTC, 13r0ck commented
I don't think I am getting the same

<details open>
<summary>Logs</summary>
<br>

```

Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:54] Startup - updater built Jul 20 2021 22:25:51
Dec 17 13:59:56 pop-os steam.desktop[4533]: ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Using the following download hosts for Public, Realm steamglobal
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] 1. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Verifying installation...
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Unable to read and verify install manifest /home/system76/.steam/debian-installation/package/steam_client_ubuntu12.installed
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Verification complete
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Downloading Update...
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Checking for available update...
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Downloading manifest: http://media.steampowered.com/client/steam_client_ubuntu12
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Downloaded new manifest: /client/steam_client_ubuntu12 version 1639697812, installed version 0, existing pending version 0
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file tenfoot_misc_all.zip.1ca83d76835b4613170f5cead778b176b11f2b0c missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file tenfoot_dicts_all.zip.33245b7d523f68418283e93b0572508fa127ee8f missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file tenfoot_fonts_all.zip.vz.7673e4cd32b6752bc621d8bc1a7118a9af19b64a_12077027 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file tenfoot_ambientsounds_all.zip.89b80bcfdd11b2b99257ddbbdc374e2df54e2738 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file tenfoot_sounds_all.zip.vz.ffef2b2fc386819a842ea79484b966a937c2ca7e_1209792 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file tenfoot_images_all.zip.vz.3068f03284bffd434b35a595a4075a61908f0f90_32858345 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file tenfoot_all.zip.vz.65063504fedb29e796026d308239539c03da342c_2348463 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file friendsui_all.zip.vz.75c7388697c21683a0b17fe3124eec03f6fa37a5_2519769 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file steamui_websrc_all.zip.vz.e9c40520f726151c686707844b995ee319c1340f_5227133 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file resources_misc_all.zip.vz.4a1fa88d21b005b67a41a9a0fc6044ae1fa46791_2225211 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file resources_music_all.zip.vz.7a62e15083d4a65668f0d1fa58ad8c1b99fb5ace_3708050 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file resources_hidpi_all.zip.vz.a6ec169f53f3e3efaebc05c1a68c1aeb567c5847_57918 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file resources_all.zip.vz.37537925c28088bb9f01b4270192b3c89e4aca5a_1313882 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file strings_en_all.zip.be2bdf334a4451b35df95dbc76d82ebad85ab824 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file strings_all.zip.vz.ee07ef0df98f88ad157e33b3ef375d6eaf1da6cf_1931609 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file public_all.zip.vz.4c64bf9fe324506063bf016189409ad26cc62d22_8865644 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file bins_ubuntu12.zip.vz.cd06e1f3f7775c0cc02fa1d3d816d405ea8eab51_26344752 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file bins_pub_ubuntu12.zip.vz.1935d2d65c88c476456534721e466748db1254c1_9052732 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file bins_sdk_ubuntu12.zip.vz.e5e676d6fb1c23b676c6ad2a26b0d2c36b381c3a_16076109 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file bins_codecs_ubuntu12.zip.vz.5ceed5368c741104f3765c20779c031d82eeebb2_5637451 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file bins_misc_ubuntu12.zip.vz.ee4c8c64fc59ac8ba94c7ed3207caf95f1987f91_17129905 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file webkit_ubuntu12.zip.vz.b4205aba571ddb8eb3601d1f69dc0551623496fe_70823591 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file miles_ubuntu12.zip.vz.4fd048667c97ef6eb976f4c42ce5c18f8695ac9e_295483 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file sdl2_ubuntu12.zip.vz.615aad349282da28e37216386085557c298367a3_2075066 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file steam_ubuntu12.zip.vz.51780f1771860e616ee5c6d0687930511590054f_2172471 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file runtime_part0_ubuntu12.zip.851ea75da169c6a07887c78681a7b34eacb78bcc missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file runtime_part1_ubuntu12.zip.26ef744f0aff46774cc2a9f56887fd4dc32bf075 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Package file runtime_part2_ubuntu12.zip.39cabdccff805dd4874831c4916dcbc6f801c181 missing or incorrect size
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Add pending download: http://media.steampowered.com/client/tenfoot_misc_all.zip.1ca83d76835b4613170f5cead778b176b11f2b0c
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Add pending download: http://media.steampowered.com/client/tenfoot_dicts_all.zip.33245b7d523f68418283e93b0572508fa127ee8f
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Add pending download: http://media.steampowered.com/client/tenfoot_fonts_all.zip.vz.7673e4cd32b6752bc621d8bc1a7118a9af19b64>
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:56] Add pending download: http://media.steampowered.com/client/tenfoot_ambientsounds_all.zip.89b80bcfdd11b2b99257ddbbdc374e2df5>
lines 1-45...skipping...
-- Journal begins at Fri 2021-12-17 13:44:47 MST, ends at Fri 2021-12-17 14:04:01 MST. --
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:54] Startup - updater built Jul 20 2021 22:25:51
Dec 17 13:59:56 pop-os steam.desktop[4533]: ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
Dec 17 13:59:56 pop-os steam.desktop[4533]: [2021-12-17 13:59:55] Using the following download hosts for Public, Realm steamglobal
Dec 17 [...]

2021-12-17 21:13 UTC, jackpot51 commented
@crawfxrd This looks like something in the way we launch things in dedicated graphics mode when using dedicated graphics is broke. Launching from CLI works, launching from launcher does not.

2022-01-07 22:15 UTC, vmavromatis commented
Sorry to jump in - but is there any ETA or progress made here? 495 has been out for while now and still unavailable on pop os. Thank you

2022-01-08 17:08 UTC, jackpot51 commented
We don't release drivers with bugs. The steam issue mentioned before is still present.

2022-01-26 19:27 UTC, jackpot51 commented
@pop-os/quality-assurance I sync'd with Ubuntu's version in the last commit. It may improve things with Steam.

2022-01-28 21:56 UTC, 13r0ck requested changes
Launching steam is still broken on newest commit.

2022-02-03 19:00 UTC, gabriele2000 commented
510 version?

2022-02-14 22:18 UTC, jackpot51 commented
Obsoleted by #134

2022-02-14 22:18 UTC, closed without merging